### ISSUE TITLE
implement question list page (Top page) 

### ISSUE THREAD

**Issue by aAkioFujita** [aAkioFujita/stackoverflow_clone_fujita#18]
Topページの実装
- [x] サンプルデータの取得と表示
  - [x] サンプルデータの作成

**Comment by aMasakiTakahashi** [comment]
いくつか実装のヒントになりそうな情報を書いておきます。
(Topページ = 質問一覧ページを前提に書いていますが、他のページの実装にも関連する内容です。)

* (質問などを格納する)collectionは下記のいずれかの方法で作成ください(作成するのはdedicated collectionのtypeがdataのものです。)
  * [DodaiのAPI](https://github.com/access-company/Dodai-doc/blob/master/collection_setting_api.md#create-a-new-dedicated-collection-setting-of-an-app)を直接curlで叩く
  * ac_console上で作成する
    * Dodai app選択 => Dedicated data collection setting => Create a new data collection
* Dodaiからquetionを取得する -1
  * [ここ](https://github.com/access-company/haro/blob/master/web/controller/voltage_history.ex#L16)の実装が参考になります。

1について下記に説明します。
* gearへのrequest parameterのvalidation
  * [Croma](https://github.com/skirino/croma)を用いて[ここ](https://github.com/access-company/haro/blob/master/lib/type/get_voltage_history_param.ex)でrequestのStructを宣言的に定義しています。
  * Cromaを用いると上記のように定義することにより、それに応じた`new/1`関数を定義してくれます。
  * それを受けてここではその`new/1`関数を適用しています。エラーになった場合はこの時点で400を返しています。
  * CromaはACCESSの多くの案件で使われているので、覚えておくと便利です。
  * 参考として紹介したgearではstructの宣言は別ファイルに記述していますが、controllerと同じファイルで書いてしまっていいと思います。
* dodaiへのrequest
  * [ここ](https://github.com/access-company/haro/blob/master/web/controller/voltage_history.ex#L21)から`Sazabi.G2gClient`を用いてDodaiへのrequestを行っています。
  * [ここ](https://github.com/access-company/haro/blob/master/web/controller/voltage_history.ex#L21)でrequsetの際のrequest parameterを決定し、[ここ](https://github.com/access-company/haro/blob/master/web/controller/voltage_history.ex#L23)で実際にリクエストしてます。
  * その後、responseの型によって処理を分けています。ここはgearによって処理が異なると思います。(そのまま返す or 加工して返す or さらにdodaiに別のrequestするなどなど)
* その他
  * dodaiのroot keyなどの認証情報はコード上に直接コーディングしないようにしてください
    * [ここ](https://github.com/access-company/haro/blob/master/web/controller/voltage_history.ex#L17)のようにgear configから取得するようにお願いします。
    * gear configについては[ここ](https://github.com/access-company/solomon/blob/master/doc/gear_developers/gear_config.md)を参照ください。
  * コーディングとは関係ないですが、masterにmergeする場合は下記としてください。
    * squash mergeを使う
      * mergeするとgithub上のnetworkがみにくくなり、masterのcommitの数が増えて視認性が悪くなるためです。
    * 必要なくなったbranchは削除する

もし分からないところがあればご連絡ください。
